refactor to remove docker builds from terraform
spacetelescope/calcloud pull request #130
Opened 2021-06-16 19:42 UTC by bhayden53

* adds variables to deploy.sh so that local source dirs can be used for build (developer convenience)
* modifies blackboard lambda to fire every 7 minutes instead of 5 (hopefully dealing with snapshot file corruption)
* refactors model training Dockerfile for readability (confirmed the image is the same size)
* removed a step from the python build-from-source in the Dockerfile that took 5 minutes to run python tests
* bugfix for ingest.py when no data is scraped

2021-06-16 22:16 UTC, alphasentaurii commented on terraform/deploy.sh
> +if [ -z "$CALCLOUD_BUILD_DIR" ]
Not a huge deal but maybe would put the mkdir and cd for $TMP_INSTALL_DIR inside the conditional (if I set $CALCLOUD_BUILD_DIR to something the script still builds and changes into a tmp dir before checking if a custom build dir was set) i.e. these come before the conditional but should go inside it
`# variables that will be changed less-frequently
TMP_INSTALL_DIR="/tmp/calcloud_install"
mkdir $TMP_INSTALL_DIR
cd $TMP_INSTALL_DIR`

2021-06-16 22:35 UTC, alphasentaurii commented on modeling/Dockerfile
>  RUN ln -s /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/ssl/certs/ca-bundle.crt && ln -s /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/ssl/certs/ca-certificates.crt && mkdir -p /etc
You've got the certs in there twice it looks like: lines8-10 and 39 (causes an error during build bc file already exists)

2021-06-16 22:49 UTC, alphasentaurii requested changes
couple of duplicate lines in Modeling docker file that should be removed. Potential minor revision to deploy.sh (non-critical)

2021-06-16 22:49 UTC, alphasentaurii commented on modeling/Dockerfile
>  RUN DEBIAN_FRONTEND=noninteractive && NCORES=`nproc` && apt update && apt upgrade -y && apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev li
Need to delete line 40 as well (duplication causes everything to install twice) - BTW you can get rid of the NCORES=`nproc` arg since we're no longer running the command that calls it ("make -j $NCORES")

2021-06-17 13:12 UTC, bhayden53 commented on terraform/deploy.sh
> +if [ -z "$CALCLOUD_BUILD_DIR" ]
fixed via https://github.com/spacetelescope/calcloud/pull/130/commits/b6b7380b3fd47db8e2dfe43373bf7535e1ce41d9

I ended up just putting a mkdir in each conditional with a -p, although probably it's more straightforward to do an or on the two custom directories to see if the tmp directory is needed at all.

2021-06-17 13:14 UTC, bhayden53 commented on modeling/Dockerfile
>  RUN DEBIAN_FRONTEND=noninteractive && NCORES=`nproc` && apt update && apt upgrade -y && apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev li
also addressed in https://github.com/spacetelescope/calcloud/pull/130/commits/67683ff8ab5d03cd632ff8996deda972b87bb3ed

2021-06-17 13:15 UTC, bhayden53 commented on modeling/Dockerfile
>  RUN ln -s /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/ssl/certs/ca-bundle.crt && ln -s /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/ssl/certs/ca-certificates.crt && mkdir -p /etc
good catch, I think this was due to the merge issue I had with vs-code. fixed in https://github.com/spacetelescope/calcloud/pull/130/commits/67683ff8ab5d03cd632ff8996deda972b87bb3ed

2021-06-17 14:23 UTC, alphasentaurii approved these changes

2021-06-17 15:44 UTC, merged